output
= RESTART: C:/Users/vamsi kumar/AppData/Local/Programs/Python/Python311/day 2 08.py
enter the number:6
The factorial of 6 is 720
The Number of factors of 6 are: 4

= RESTART: C:/Users/vamsi kumar/AppData/Local/Programs/Python/Python311/day 2 08.py
enter the number:0
The factorial of 0 is 1
The Number of factors of 0 are: 0

= RESTART: C:/Users/vamsi kumar/AppData/Local/Programs/Python/Python311/day 2 08.py
enter the number:-5
Sorry, factorial does not exist for negative numbers
The Number of factors of -5 are: 0

= RESTART: C:/Users/vamsi kumar/AppData/Local/Programs/Python/Python311/day 2 08.py
enter the number:1
The factorial of 1 is 1
The Number of factors of 1 are: 1

= RESTART: C:/Users/vamsi kumar/AppData/Local/Programs/Python/Python311/day 2 08.py
enter the number:20
The factorial of 20 is 2432902008176640000
The Number of factors of 20 are: 6

= RESTART: C:/Users/vamsi kumar/AppData/Local/Programs/Python/Python311/day 2 08.py
enter the number:3A
Traceback (most recent call last):
  File "C:/Users/vamsi kumar/AppData/Local/Programs/Python/Python311/day 2 08.py", line 1, in <module>
    num = int(input("enter the number:"))
ValueError: invalid literal for int() with base 10: '3A'